

import os
import os.path

def tidy(filename) :
    with open(filename, 'r+') as f :
        contents = f.readlines()
        deleteIndex = -1
        for i, line in enumerate(contents) :
            if line.strip().startswith("<!-- Generated by javadoc") :
                deleteIndex = i
                break
        if deleteIndex >= 0 :
            del contents[deleteIndex]
            f.seek(0)
            f.truncate()
            f.writelines(contents)

if __name__ == "__main__" :
    websiteRoot = sys.argv[1]

    os.chdir(websiteRoot)

    allFiles = []
    for root, dirs, files in os.walk(".") :
        for f in files :
            if len(f) >= 5 and ".html" == f[-5:] :
                allFiles.append(os.path.join(root, f))

    for f in allFiles :
        tidy(f)
    
